steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dotnet-cloud-run/umbraco13:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dotnet-cloud-run/umbraco13:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'dotnet-cloud-run', '--region=europe-north1', '--platform=managed', '—image=gcr.io/dotnet-cloud-run/umbraco13:$SHORT_SHA']
